server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/celia-auth-realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  application:
    name: auth-service

app:
  keycloak:
    serverUrl: http://localhost:8080
    realm: celia-auth-realm
    clientId: celia-auth-client
    clientSecret: 15o0ClbLC4ZSQzCZYj4360EfOM4mPCqN
