server:
  port: 8081

spring:
  application:
    name: auth-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.keycloak.server-url}/realms/${app.keycloak.realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

app:
  keycloak:
    server-host: localhost
    server-port: 8080
    server-url: http://${app.keycloak.server-host}:${app.keycloak.server-port}

    admin-realm: master
    admin-client-id: admin-cli
    admin-username: admin
    admin-password: admin

    realm: celia-auth-realm
    client-id: celia-auth-client
    client-secret: client-secret
